### ISSUE TITLE
Review add-fission-support branch and get it working

### ISSUE THREAD

**Issue by bmann** [fission-suite/ipfs-deploy#1]
Boris cut-and-paste his way to copying how Pinata / Infura work. Please review his work, and troubleshoot to get it working.

Was getting some errors around Axios, but also it might just be simple syntax errors, since @bmann literally just cuts and pastes his way through NodeJS.

**Comment by expede** [comment]
@expede likes how @bmann speaks in the third-person 😛

**Comment by dholms** [comment]
Check this out, see if it works on your end: https://github.com/fission-suite/ipfs-deploy/commit/859ad391a444bb0a15fab987e4ff776a89d2fca3

**Comment by dholms** [comment]
.env should look like:
```
IPFS_DEPLOY_FISSION__USERNAME = abcdefg
IPFS_DEPLOY_FISSION__PASSWORD = 123456789
```

**Comment by bmann** [comment]
OK! Good news / bad news. Runs without errors, but seems to prepend content to uploaded files? I am closing this.
